name: Build WASMs

on:
  push:
    branches: [main]
    tags:
      - 'wasm-prebuilds-*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Setup emsdk
        run: sudo ./build/setup-emsdk.sh

      - name: Add emsdk to PATH
        run: |
          echo "/opt/dev/emsdk" >> $GITHUB_PATH
          echo "/opt/dev/emsdk/upstream/emscripten" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm ci --force

      - name: Build all wasm
        run: npm run build-wasm

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v6
        with:
          name: wasm-artifacts
          path: wasm/
